# Generated by Django 4.1.1 on 2023-12-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_url_request_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=50),
        ),
    ]
